### PR TITLE
CLI: change unit test for MVC apps not to use MockRouter

### LINKED ISSUE #1917: MockRouter does not support MVC Coroutines
It seems like the CoroutineRouter might make a few different assumptions around not using the MVC mode in general, but the main one blocking us at the moment is the MockRouter not working properly.

I see this commit fixed this for the other mode by setting a new attribute: https://github.com/jooby-project/jooby/commit/8ed3364810a811844095fdf4182ecbf7b81d8c05

But it appears it wasn't implemented for the MVC side of things - am I understanding that correctly?

Thanks!

### PR DESCRIPTION
**Pull request by imeszaros**
May close #1917

### CODE REVIEW

**Comment by jknack** [comment]
Thanks!, what if we provide a real unit test for mvc controller?

**Comment by imeszaros** [comment]
I was considering it but not exactly clear how should it look like exactly.

**Comment by jknack** [comment]
I looked at the generated code and it is just:

```
import io.jooby.annotations.*;

@Path("/")
public class Controller {

  @GET
  public String sayHi() {
    return "Welcome to Jooby!";
  }
}
```

So unit tests should be very simple...not sure if useful

**Comment by imeszaros** [comment]
So just a simple test against the controller class, no jooby logic involved? ok I can do that.

**Review by jknack — APPROVED** [review]

**Pull request merged**
