### PR TITLE
Making the src extensions that trigger rebuild configurable

### PR DESCRIPTION
**Pull request by sphogan**
This will allow people to configure the src extensions that trigger rebuild so that they can add Kotlin or Rocker file extensions to trigger re-compilation.

### CODE REVIEW

**Comment by jknack** [comment]
Can you please document the new property for maven and gradle?

You will find documentation inside the `/doc` folder as markdown files

Thanks

**Comment by jknack** [comment]
Oh and can you please add `.kt` as default lookup extension too?

**Comment by sphogan** [comment]
I've added documentation, made `.kt` a default lookup extension, and altered `JoobyMojo` so that it will do the same XML footwork that `JoobyTask` is doing.

I had tested it with Gradle and Kotlin and with Maven and Rocker, but I hadn't tested Maven with Kotlin and there was an issue with the classpath on subsequent runs that would cause re-compilation to fail.

Let me know if you want any other changes and thanks for a truly wonderful project.

**Comment by jknack** [comment]
@sphogan can you rebase and update? (sorry, for taking so long to merge it)

**Comment by sphogan** [comment]
I've rebased it onto the current master.  Thanks for the excellent project!

**Pull request merged**
