### PR TITLE
UnitOfWork port from 1.x

### PR DESCRIPTION
**Pull request by imeszaros**
See #1920

### CODE REVIEW

**Comment by imeszaros** [comment]
Not really but i have no better candidate... maybe we could stick with UnitOfWork.. :) If you like this how it is now i'll write some docs later (once the name is final).

**Comment by imeszaros** [comment]
I changed the name back to `UnitOfWork` and added docs.

**Comment by jknack** [comment]
What if we copy (more or less) https://docs.spring.io/spring/docs/2.5.x/javadoc-api/org/springframework/orm/jpa/JpaTemplate.html and https://docs.spring.io/spring/docs/2.5.x/javadoc-api/org/springframework/orm/jpa/JpaCallback.html from Spring?

**Comment by imeszaros** [comment]
You mean the name only, or the code/behavior too?

I can do that, but these classes were deprecated as of Spring 3.1, they recommend using the `EntityManager` directly. My personal opinion is that your approach with Jooby to be mostly minimalist and as invisible as possible is really great thing. We should not hide/wrap the JPA API, just provide some convenience around it.

I think `UnitOfWork` in 1.x was cool, we successfully brought several (mid to big) projects to life using it. The only feature we missed is the ability to handle multiple transactions, and the inconvenience that it declared to throw exception, these things i've tried to address in this PR.

Maybe it would be good to hear other hibernate user's opinion about this too.

If you wish I could try to bring these classes in instead, but in this case our team would probably stick with our custom extension.

**Comment by jknack** [comment]
Yea, good points. Doubt any one else is going to provide feedback :D

For now, let's merge it.

Thank you.

**Pull request merged**
