### PR TITLE
Gradle Plugin: Towards hot-reloading for Kotlin

### PR DESCRIPTION
**Pull request by nlochschmidt**
Related to #761 

This should be seen as a first step towards full Kotlin hot-reload support in Gradle, but it already works when the Kotlin sources are alongside the Java sources under `/src/main/java`. According to the Kotlin Gradle plugin docs it is a valid location for Kotlin sources: https://kotlinlang.org/docs/reference/using-gradle.html#android-studio

It's certainly better than no hot-reloading at all 😉

### CODE REVIEW

**Comment by jknack** [comment]
does compilation works once you changed a .kt file?

**Comment by nlochschmidt** [comment]
Yes, as long as the the .kt file is in the Java source folder.

**Comment by jknack** [comment]
What version of gradle? Remember it didn't work before

**Comment by nlochschmidt** [comment]
Uh, ok. I tried it using my fork of the kotlin-starter that uses gradle version 3.4. You can get the configuration I used for testing from https://github.com/nlochschmidt/kotlin-starter/tree/auto-reload-test (Branch auto-reload-test)

**Comment by nlochschmidt** [comment]
I forgot to create a branch on my fork of jooby before opening the pull request. I now needed to sync it with upstream so the PR got closed. In any case there wasn't much code here anyway, just this: https://github.com/nlochschmidt/jooby/commit/0b9d9861f7c5d5e483151ec9723048bf7051ace0

**Pull request closed without merging**
