### PR TITLE
hikariCP.version upgrade

### PR DESCRIPTION
**Pull request by paul-hammant**

### CODE REVIEW

**Comment by jknack** [comment]
did you run: `./build/coverage.sh`?

JooqFeature.java is failing.

**Comment by paul-hammant** [comment]
I just do a 'mvn clean install' from the top. I'll do coverage.sh going forwards. Including for this one.

**Comment by paul-hammant** [comment]
Yup coverage report fails for that. It's inexplicable to me though :-(

Do you debug that through Intellij with a profile set.  Does it adequately setup the classpath in the same way that the Maven command line does?  I mean so that you can quickly solve towards root cause methodically.

**Comment by jknack** [comment]
Closing in favor of #1031

**Pull request closed without merging**
