### PR TITLE
Some copy editing on the first few paras.

### PR DESCRIPTION
**Pull request by nikos**
Hope this helps a bit :)

### CODE REVIEW

**Comment by jknack** [comment]
Thanks! Can you makes the changes in https://github.com/jooby-project/site-generator/tree/master/src/main/resources/site

That's the `source code` of the website and we need to apply the changes there too. Otherwise, this will be overwritten in the next release.

**Comment by nikos** [comment]
Ah I see, sorry I didn't take the the time to look up the sources, will fix it in the site-generator project for sure, though a bit later/tomorrow since I am on the rush now ...

**Comment by jknack** [comment]
np, thanks a lot.

**Comment by nikos** [comment]
Hi Edgar, when trying to lookup to original files in the `site-generator` repo (`master` branch) `src/main/resources/site` that it seems not to reflect the docs that are currently published at jooby.org (could you please double check that everything is checked in and pushed)?

**Comment by jknack** [comment]
It should be up to date, pushed yesterday. Can you give me an example?

**Comment by jknack** [comment]
Wait! I got it! and you're right, it wasn't up-to-date bc we were pushing directly to gh-pages. With the pull you send to site-generator everything will be async

**Comment by jknack** [comment]
Closing this pull in favor of https://github.com/jooby-project/site-generator/pull/5

**Pull request closed without merging**
