### PR TITLE
[WIP] New pac4j2 module 

### PR DESCRIPTION
**Pull request by lodrantl**
This pull request tracks the progress on the new pac4j module, which reuses more of the pac4j code and works in the same way as other pac4j implementations do.  Had to remove other pac4j modules due to dependency conflicts. 

So far there is some basic functionality, but it will not build due to old test code. Currently working on that.

### CODE REVIEW

**Comment by ajcamilo** [comment]
Is there an ETA for this feature to finish?

**Comment by jknack** [comment]
Yes, finally found sometime to review work done by the guys... I clean up and review the new pac4 2 API.

The module is ready, just finishing tests + doc.

**Comment by jknack** [comment]
Merged in master. Thanks all

**Comment by lodrantl** [comment]
Thanks for finishing it off :+1:

**Pull request closed without merging**
