### PR TITLE
New API Tool implementation

### PR DESCRIPTION
**Pull request by jknack**
Usage:

```java
use(new ApiTool()
        .raml("/raml")
        .swagger("/swagger"));
```

The new API Tool comes with:

+ Java/Kotlin support for script routes
+ The new script parser works at byte code level
+ More powerful Javadoc parser for Java and Kotlin
+ Javadoc is fully optional
+ All the existing/reported issues from spec where migrated and tested
+ Latest swagger UI
+ API Console 3.x for Raml (we can't use or easily add 4.x yet). See https://github.com/mulesoft/api-console/issues/523
+ UI Themes for Swagger and Raml

TODO:
- Maven/Gradle integration
- Javadoc for new API
- Documentation for new module

I'm going to leave the pull open for a week if someone want to have a closer look

Swagger:
image

Raml:
image

### CODE REVIEW

**Comment by ajcamilo** [comment]
can you please give some more info on how to use this new api? 

Should we still generate de RAML file with maven?

btw, thanks for this :)

**Comment by jknack** [comment]
Here is an example: https://github.com/jooby-project/jooby/blob/659900c7615cf1095ce08716a4d57964a5045241/modules/jooby-apitool/src/test/java/apps/AppWithDoc.java

Yes, you need maven/gradle to keep documentation.

The new API allows you to customize Swagger/Raml. Here is your use case around UUID:

```java
use(new ApiTool()
  .raml("/raml", raml -> {
    RamlType uuid = raml.define(UUID.class, RamlType.STRING);
    uuid.setPattern("...");
  });
);
```

And there is more, you can fix/change API results directly:
```java
use(new ApiTool()
  .raml("/raml", raml -> {
    RamlMethod method = raml.path("/pet").method("get");
    method.setBody(MyCustomResponseType.class);
  });
);
```

Same for swagger but using the official Swager libraries

**Comment by ajcamilo** [comment]
In the example of the UUID, that customization will be used just by the jooby-maven-plugin, am I right?
Because it says how to generate the RAML spec file.

Until the jooby-maven-plugin uses this new ApiTool, I can really test my use case. Or can I?

**Comment by jknack** [comment]
No. Definition files (api.raml, swagger.json) are part of the application runtime and they are exposed via HTTP routes, the internal representation of them is the one that is generated by Maven/Gradle plugin. This works as today, except for we moved from a binary to json format for the internal representation.

Modification of internal or target (swagger/raml) representation are done at runtime.

You can tested the new module today, without the maven plugin by using this branch.

**Comment by jknack** [comment]
@ajcamilo did you try it? All good?

**Comment by ajcamilo** [comment]
I'm having the following error and I don't know why:

```
1) Error injecting constructor, java.lang.NoClassDefFoundError: org/jooby/internal/apitool/asm/util/$Printer                            
  at org.jooby.internal.apitool.APIProvider.<init>(APIProvider.java:21)                               
  while locating org.jooby.internal.apitool.APIProvider                                                                                  
  while locating java.util.List<org.jooby.apitool.RouteMethod>                                                                           
                                                                                                                                         
1 error                                                                                                                                  
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)                                                         
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)                                                   
        at org.jooby.internal.RequestImpl.require(RequestImpl.java:484)                                                                  
        at org.jooby.Registry.require(Registry.java:253)                                                                                 
        at org.jooby.apitool.ApiTool.lambda$raml$1(ApiTool.java:389)                                                                     
        at org.jooby.Route$OneArgHandler.handle(Route.java:1994)                                                                             
        at org.jooby.internal.RouteImpl.handle(RouteImpl.java:282)                                                                                   
        at org.jooby.internal.RouteChain.next(RouteChain.java:262)                                                                                                                        
        at org.jooby.Route$Chain.next(Route.java:2340)                                                                                                                                    
        at org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:497)                                                                                                            
        ... 9 common frames omitted                                                                                                                                                       
Caused by: java.lang.NoClassDefFoundError: org/jooby/internal/apitool/asm/util/$Printer                                                                                                   
        at org.jooby.apitool.ApiParser.parse(ApiParser.java:247)                                                                                                                          
        at org.jooby.internal.apitool.APIProvider.<init>(APIProvider.java:22)                                                                                                             
        at org.jooby.internal.apitool.APIProvider$$FastClassByGuice$$9b325895.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
        ... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.jooby.internal.apitool.asm.util.$Printer from [Module "com.premiumminds.jiffy.group.backend:main" from AppModuleLoader@1522476d for finde
rs []]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
        ... 29 common frames omitted
```

**Comment by jknack** [comment]
Odd, need to review how jarjar is bundling asm.

Good catch!

**Comment by jknack** [comment]
@ajcamilo can you please try again. All should be good now.

**Comment by ajcamilo** [comment]
I've tried and now works.

The only problem I'm having is that, with my body class like this:
```java
public class Client {
    private UUID id;
    private String name;
    ...
}
```
And defining the ApiTool like this:

```java
        use(new ApiTool().raml("/raml", raml -> {
            RamlType uuid = raml.define(UUID.class, RamlType.STRING);
            uuid.setPattern(
                    "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12" +
                            "}$");
        }));
```
The `UUID` is defined in the RAML spec, but the "id" is set as a string.
```
  Client:
    type: object
    properties:
      id?: string
      name?: string
    example:
      id: string
      name: string
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
```

**Comment by jknack** [comment]
@ajcamilo Thanks again for trying the new module. All good now, let me know if you have questions

**Pull request merged**
