### PR TITLE
validation: cleanup

### PR DESCRIPTION
**Pull request by jknack**
- make constrainctvalidation cast safe
- use config api for properties
@SentryMan can you look at locales?

### CODE REVIEW

**Review by SentryMan — APPROVED** [review]
LGTM, the validator should use the default system locale if none are provided

**Comment by kliushnichenko** [comment]
@jknack Don't you want to add some `.editorconfig` to avoid manual code re-formatting? And maybe some contribution guide

**Comment by jknack** [comment]
we should add it yea. Today it uses spotless + git pre-commit hook that is installed on `mvn clean package`

**Comment by SentryMan** [comment]
I'm in the minority, but I use Eclipse, so `.editorconfig` doesn't do anything for me.

**Pull request merged**
