### PR TITLE
 Annotations inheritance in MVC routes #1552

### PR DESCRIPTION
**Pull request by franklx**
Implementation works as expected and supports inherited MVC routes as Jooby-1.x.
Commit includes passing test for issue #1552 .

### CODE REVIEW

**Comment by franklx** [comment]
Oh, well... I'm quite stuck!
I didn't know that ```com.sun.tools.*``` isn't available in jdk8.
Any advice is welcome...

**Comment by jknack** [comment]
I didn't look closely... but yes we can;'t use `com.sun` due it is an internal API

There should be a way of doing what you did using the public API: `javax.lang.model.*`

**Comment by jknack** [comment]
An alternative solution will be to call all the types as we do today and before we finish check for type and super/sub type and merge and remove as accordingly.

but again I did look yet

**Comment by franklx** [comment]
Public API doesn't seem to allow instantiating or cloning ```Element```s.
A possible solution is to modify ```class HandlerCompiler``` forcing the child class as "mock" owner.
I've investigated that possibility before but the Symbol API offered a cleaner solution.
I'll look at it.

**Comment by franklx** [comment]
I managed removing the internal class dependencies processing classes at the end as you suggested.
It all works perfectly except of a class name problem (see travis log).
I'm not sure how to correct the problem: should I fix the test code or should I change the class name removing parent?
Assertion failing is:
```java
assertEquals(factoryName, new String(Files.readAllBytes(services), StandardCharsets.UTF_8).trim());
```
in ```jooby-apt/src/test/java/io/jooby/apt/MvcModuleCompilerRunner.java```.

Thank you

**Comment by franklx** [comment]
Finally I've changed the META-INF/services file generation limiting to the first generated class.
Please let me know if this can be good.
Thank you

**Comment by jknack** [comment]
Think we should generated it as long as the controller class is not abstract..hmmm... or probably better to generate leaf subclass?

If we generate for none abstract class the binding is up to final user: `mvc(new Controller())`, drawback is that we may have N generated class if the parent class isn't abstract while the leaf subclass generation generates a single entry per each leaf subclass.

**Comment by franklx** [comment]
What I did is wrong and only works only with abstract classes.
META-INF/services generation must be left alone, I'll try fixing test function.

**Comment by franklx** [comment]
Test function fixed.

**Comment by jknack** [comment]
Cool, are you done?

**Comment by franklx** [comment]
Yes, it works and passes all tests.
Anyway it can be good if you take a closer look to the diff... I worked on quite sensitive code.

**Comment by jknack** [comment]
Will do. Thanks for contributing!

**Pull request merged**
