### PR TITLE
Updates Ebean to latest versions (10.x)

### PR DESCRIPTION
**Pull request by huysamen**

### CODE REVIEW

**Comment by jknack** [comment]
I took too long to merge it (sorry) and now can't be merge it

Can you rebase and update your pull?

Please let me know, otherwise will see how to apply your commits to master.

Thanks and sorry again.

**Comment by huysamen** [comment]
No worries.  Rebased, patched and updated Ebean to latest version (+1 patch version).  I also updated HikariCP to the latest for the following change releases in 2.6.0 which is pretty great:

_Redesign of the contention code path resulting in doubling contended throughput; now contended pool access retains 98% of the uncontended throughput._

**Comment by jknack** [comment]
Your pull contains some already merged commits.. don't worry I'm going to pick your commits and merge your changes, but probably have to close this pull.

Thanks.

**Comment by jknack** [comment]
Replaced by #673

**Pull request closed without merging**
