### PR TITLE
add sonarcloud analysis from travis

### PR DESCRIPTION
**Pull request by JeffLeFoll**
Hi, this PR is related to issue #1197 .

You can see the resulting sonar analysis result here : https://sonarcloud.io/dashboard?id=jfl-sonar-jooby-test

Please not that in order to work you need to set in Travis an Env. variable called SONAR_TOKEN with your token configured in sonarcloud.

The code coverage % is not the same in sonar and coveralls because coveralls is configure to only analyse some packages and sonar take the whole sources in account.

It maybe possible to configure sonar to only take a sub-set of the sources in account.

### CODE REVIEW

**Comment by Daniel-Dos** [comment]
very good .

**Comment by Daniel-Dos** [comment]
@jknack please review .

**Comment by jknack** [comment]
Thank you, for this. I tried a lot without luck, I was missing the `sonar.jacoco.reportPaths` variable.

**Comment by JeffLeFoll** [comment]
You're welcome, I'm glad to have been helpful :)

But just to make it clear, with this configuration you will have a huge difference on the % of coverage between sonar and coveralls.

This is due to the fact that coveralls is configured to only take into account a small set of jooby's source whereas sonar will take into account all the sources (for instance event modules without tests).

It may be possible to configure sonar to excludes some sources.

**Comment by jknack** [comment]
Make senses, need to work a bit more to sync both coverage. The code we skip is basically:

- code I took from somewhere else, like Netty SSL
- awful code from ApiTool (bytecode parsing)

**Comment by JeffLeFoll** [comment]
Ok, I will try to add the configuration to exclude some sources that don't make sense.

**Comment by jknack** [comment]
Thanks. These are the classes we skip: https://github.com/jooby-project/jooby/blob/master/modules/coverage-report/pom.xml#L202-L213

As said, not all the project are covered. Complete list of covered projects is here: https://github.com/jooby-project/jooby/blob/master/modules/coverage-report/pom.xml#L39-L94

**Pull request closed without merging**
