### PR TITLE
Add advice on building Jooby

### PR DESCRIPTION
**Pull request by paul-hammant**

### CODE REVIEW

**Comment by jknack** [comment]
Thank you, can you add a note for https://github.com/jooby-project/jooby/blob/master/build/coverage.sh

It helps to see and visualize code coverage

**Comment by paul-hammant** [comment]
Not sure what you're asking me, Edgar - the two changes files are markdown, not Java source files

**Comment by jknack** [comment]
Hi @paul-hammant 

Please remove the https://github.com/jooby-project/jooby/pull/824/commits/f6d830afd588a477585dbe641f6bf4c1f003ac4f commit.

Thanks

**Comment by paul-hammant** [comment]
I separated that other change out - it's not on a issue812 branch that as you say isn't pertinent to this PR

**Comment by paul-hammant** [comment]
Hey Edgar - I think this one is ready for you to merge in now.

**Comment by paul-hammant** [comment]
yay!

**Pull request merged**
