### PR TITLE
upgrade jetty to v9.4.6

### PR DESCRIPTION
**Pull request by paul-hammant**

### CODE REVIEW

**Comment by paul-hammant** [comment]
Thoughts @jnack ?

**Comment by jknack** [comment]
version bump isn't enough :(

need a closer look to see why failing

**Comment by paul-hammant** [comment]
I'm going to trot out that "it worked for me" claim, then hang my head in shame ....

**Comment by paul-hammant** [comment]
I've just pulled all your commits to my workstation and the build still passes for me.

**Pull request closed without merging**
