### PR TITLE
Update jQuery to 2.2.4, jquery-ui to 1.12.1

### PR DESCRIPTION
**Pull request by DerDackel**
Hey there,
I did a little busywork upgrading jQuery to the latest stable 2.x release in the same vein as @feffi's version update crusade.
It's mostly a find & replace job, as the specific version of the artifact was referenced across a lot of different tests (maybe we could reduce that?). The whole thing is largely only relevant for testing but it posed a good starter, as I'm currently familiarizing myself with Jooby's test suites

### CODE REVIEW

**Comment by DerDackel** [comment]
Is there some instability with the tests on Travis? The test blowing up seems totally unrelated and I'm having a serious case of "Can't reproduce" here.

**Comment by feffi** [comment]
Yep, got some DNS errors yesterday

**Comment by jknack** [comment]
Merged @feffi pull request and this need to be rebased now... After a closer look I realize the jquery jar is used for testing large files requests... Feel we shouldn't care what version of jquery is as long we keep testing large files, no?

**Comment by DerDackel** [comment]
Yeah, that one was more my OCD. exorcised it from the commit and rebased master.

**Pull request closed without merging**
