### PR TITLE
WebSockets: #isOpen fix #574

### LINKED ISSUE #574: WebSockets: #isOpen
There is no possibility to ask the WebSocket whether it is open.
Could you delegate that method?

org.jooby.spi.NativeWebSocket#isOpen

### PR DESCRIPTION
**Pull request by jknack**
* synchronized ws access

### CODE REVIEW

**Comment by jknack** [comment]
@jschneider can you review too?

Thanks

**Comment by jschneider** [comment]
Will take a look. I hope I will find time in the next 24 hours.

**Comment by jschneider** [comment]
Looks good on the first glance.

Two things:
- "synchronized(this)": Is this how you are synchronizing in jooby? I'd prefer a lock, but of course "synchronized" should work.

- What happens if somebody writes into a closed web socket? 


I will take a closer look later.

**Comment by jknack** [comment]
Updated. I kept sync and now throw an `Err(1001=NORMAL close)` on closed web sockets

**Pull request merged**
